server:
  port: 8500
  servlet:
    context-path: /
  error:
    include-stacktrace: never
spring:
  application:
    name: i-wallet
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:./db/i-wallet;INIT=CREATE SCHEMA IF NOT EXISTS wallet\\;SET SCHEMA wallet"
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    hibernate.hbm2ddl.auto: update
  jooq:
    sql-dialect: org.hibernate.dialect.SQLiteDialect
  type: com.zaxxer.hikari.HikariDataSource
  hikari:
    pool-name: ${spring.application.name}
    maxLifetime: 600000
    idle-timeout: 300000
    connection-timeout: 10000
    maximum-pool-size: 50
    minimum-idle: 10

  h2:
    console:
      enabled: true

springdoc:
  api-docs:
    path: /${spring.application.name}/v3/api-docs
  swagger-ui:
    path: /${spring.application.name}/swagger-ui.html


